const ActionTypes = {
  EDIT_TODO: "EDIT_TODO",
  ADD_TODO: "ADD_TODO",
  DELETE_COMPLETED_TODOS: "DELETE_COMPLETED_TODOS",
  DELETE_TODO: "DELETE_TODO",
  START_EDITING_TODO: "START_EDITING_TODO",
  STOP_EDITING_TODO: "STOP_EDITING_TODO",
  TOGGLE_ALL_TODOS: "TOGGLE_ALL_TODOS",
  TOGGLE_TODO: "TOGGLE_TODO",
  UPDATE_DRAFT: "UPDATE_DRAFT",
};

export const DataStorageTypes = {
  CurrentTodoText: "CurrentTodoText",
  TodoList: "TodoList",
};

export default ActionTypes;
